// <auto-generated />
using System;
using ArmoryInventory.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ArmoryInventory.Data.Migrations
{
    [DbContext(typeof(ArmoryInventoryDbContext))]
    [Migration("20250129165523_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.1");

            modelBuilder.Entity("ArmoryInventory.Domain.Models.Checkout", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("CheckedOutTo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DateCheckedIn")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateCheckedOut")
                        .HasColumnType("TEXT");

                    b.PrimitiveCollection<string>("DefectsAfter")
                        .HasColumnType("TEXT");

                    b.PrimitiveCollection<string>("DefectsBefore")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ItemId");

                    b.ToTable("Checkouts");
                });

            modelBuilder.Entity("ArmoryInventory.Domain.Models.Item", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("CheckedOut")
                        .HasColumnType("INTEGER");

                    b.PrimitiveCollection<string>("Defects")
                        .HasColumnType("TEXT");

                    b.Property<int>("HasAllComponents")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ItemType")
                        .HasColumnType("INTEGER");

                    b.PrimitiveCollection<string>("MissingComponents")
                        .HasColumnType("TEXT");

                    b.Property<int>("MissionCapable")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SerialNumber")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Items");
                });

            modelBuilder.Entity("ArmoryInventory.Domain.Models.Checkout", b =>
                {
                    b.HasOne("ArmoryInventory.Domain.Models.Item", null)
                        .WithMany("CheckoutHistory")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ArmoryInventory.Domain.Models.Item", b =>
                {
                    b.Navigation("CheckoutHistory");
                });
#pragma warning restore 612, 618
        }
    }
}
