// <auto-generated />
using System;
using ArmoryInventory.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ArmoryInventory.Data.Migrations
{
    [DbContext(typeof(ArmoryInventoryDbContext))]
    [Migration("20250206234603_CheckoutUpdate")]
    partial class CheckoutUpdate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.1");

            modelBuilder.Entity("ArmoryInventory.Domain.Models.Checkout", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CheckedOutTo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("DateCheckedIn")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("DateCheckedOut")
                        .HasColumnType("TEXT");

                    b.PrimitiveCollection<string>("DefectsAfter")
                        .HasColumnType("TEXT");

                    b.PrimitiveCollection<string>("DefectsBefore")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ItemId");

                    b.ToTable("Checkouts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CheckedOutTo = "Captain",
                            DateCheckedOut = new DateOnly(2019, 5, 9),
                            DefectsAfter = "[]",
                            DefectsBefore = "[]",
                            ItemId = new Guid("c7bb57a3-f967-47f8-a4a4-d4529e898c25")
                        },
                        new
                        {
                            Id = 2,
                            CheckedOutTo = "Captain",
                            DateCheckedOut = new DateOnly(2020, 5, 9),
                            DefectsAfter = "[]",
                            DefectsBefore = "[]",
                            ItemId = new Guid("c7bb57a3-f967-47f8-a4a4-d4529e898c25")
                        });
                });

            modelBuilder.Entity("ArmoryInventory.Domain.Models.Item", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("CheckedOut")
                        .HasColumnType("INTEGER");

                    b.PrimitiveCollection<string>("Defects")
                        .HasColumnType("TEXT");

                    b.Property<int>("HasAllComponents")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ItemType")
                        .HasColumnType("INTEGER");

                    b.PrimitiveCollection<string>("MissingComponents")
                        .HasColumnType("TEXT");

                    b.Property<int>("MissionCapable")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SerialNumber")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Items");

                    b.HasData(
                        new
                        {
                            Id = new Guid("c7bb57a3-f967-47f8-a4a4-d4529e898c25"),
                            CheckedOut = 2,
                            Defects = "[\"Back connectors bent\",\"Front Light doesn\\u0027t work\"]",
                            HasAllComponents = 1,
                            ItemType = 2,
                            MissingComponents = "[]",
                            MissionCapable = 1,
                            SerialNumber = "111N5"
                        },
                        new
                        {
                            Id = new Guid("d507734c-1d27-438c-8cf9-7560e1aa329c"),
                            CheckedOut = 2,
                            Defects = "[]",
                            HasAllComponents = 1,
                            ItemType = 1,
                            MissingComponents = "[\"Missing 2 stakes\",\"Missing one blue pole\"]",
                            MissionCapable = 1,
                            SerialNumber = "222NF"
                        },
                        new
                        {
                            Id = new Guid("465efd68-c55d-4f49-96f0-1c7e0228c805"),
                            CheckedOut = 2,
                            Defects = "[]",
                            HasAllComponents = 1,
                            ItemType = 1,
                            MissingComponents = "[\"Missing 1 stake\",\"Missing 2 blue pole\",\"Missing Hammer\"]",
                            MissionCapable = 1,
                            SerialNumber = "272N8"
                        },
                        new
                        {
                            Id = new Guid("d441a0db-dfc7-460f-bfc5-44136dbc6a03"),
                            CheckedOut = 2,
                            Defects = "[\"Mic key does not work\"]",
                            HasAllComponents = 2,
                            ItemType = 3,
                            MissingComponents = "[]",
                            MissionCapable = 2,
                            SerialNumber = "342N7"
                        },
                        new
                        {
                            Id = new Guid("672dc07c-16e2-4871-b5ce-8c590c816f0a"),
                            CheckedOut = 1,
                            Defects = "[\"Back connectors bent\",\"Front Light does\\u0027nt work\"]",
                            HasAllComponents = 1,
                            ItemType = 2,
                            MissingComponents = "[]",
                            MissionCapable = 1,
                            SerialNumber = "233N7"
                        },
                        new
                        {
                            Id = new Guid("c7a072e9-9175-4403-8c64-be4bb8d7bb3b"),
                            CheckedOut = 2,
                            Defects = "[]",
                            HasAllComponents = 1,
                            ItemType = 1,
                            MissingComponents = "[\"Missing 2 stakes\",\"Missing one blue pole\"]",
                            MissionCapable = 1,
                            SerialNumber = "522F4"
                        },
                        new
                        {
                            Id = new Guid("98ce6fb5-9ab6-4466-b1da-2d9d2568e1a3"),
                            CheckedOut = 2,
                            Defects = "[]",
                            HasAllComponents = 1,
                            ItemType = 1,
                            MissingComponents = "[\"Missing 1 stake\",\"Missing 2 blue pole\",\"Missing Hammer\"]",
                            MissionCapable = 1,
                            SerialNumber = "442F4"
                        },
                        new
                        {
                            Id = new Guid("cc97f041-7bfb-4d12-af53-7bcd8ae2b7a2"),
                            CheckedOut = 2,
                            Defects = "[\"Mic key does not work\"]",
                            HasAllComponents = 1,
                            ItemType = 3,
                            MissingComponents = "[]",
                            MissionCapable = 1,
                            SerialNumber = "523F5"
                        },
                        new
                        {
                            Id = new Guid("54b85a9f-7b8d-4aed-ad46-28efdf0d85b4"),
                            CheckedOut = 1,
                            Defects = "[\"Back connectors bent\",\"Front Light does\\u0027nt work\"]",
                            HasAllComponents = 1,
                            ItemType = 2,
                            MissingComponents = "[]",
                            MissionCapable = 1,
                            SerialNumber = "372F4"
                        },
                        new
                        {
                            Id = new Guid("e30f58ff-46eb-452d-827c-f7af3f5a74db"),
                            CheckedOut = 2,
                            Defects = "[]",
                            HasAllComponents = 1,
                            ItemType = 1,
                            MissingComponents = "[\"Missing 2 stakes\",\"Missing one blue pole\"]",
                            MissionCapable = 1,
                            SerialNumber = "522N4"
                        },
                        new
                        {
                            Id = new Guid("8589c1b6-86d2-4202-92c9-688370f7a3b0"),
                            CheckedOut = 2,
                            Defects = "[]",
                            HasAllComponents = 1,
                            ItemType = 1,
                            MissingComponents = "[\"Missing 1 stake\",\"Missing 2 blue pole\",\"Missing Hammer\"]",
                            MissionCapable = 1,
                            SerialNumber = "624N2"
                        },
                        new
                        {
                            Id = new Guid("3c3db93c-ba89-4ec7-87b5-02d377bfa7b1"),
                            CheckedOut = 1,
                            Defects = "[\"Mic key does not work\"]",
                            HasAllComponents = 1,
                            ItemType = 3,
                            MissingComponents = "[]",
                            MissionCapable = 1,
                            SerialNumber = "623N5"
                        },
                        new
                        {
                            Id = new Guid("94368184-0101-4e9f-b9de-a8f3900d415a"),
                            CheckedOut = 1,
                            Defects = "[\"Mic key does not work\"]",
                            HasAllComponents = 1,
                            ItemType = 3,
                            MissingComponents = "[]",
                            MissionCapable = 1,
                            SerialNumber = "124N8"
                        },
                        new
                        {
                            Id = new Guid("24caa1b3-9433-4883-ad2a-ced8ee8443ef"),
                            CheckedOut = 1,
                            Defects = "[\"Back connectors bent\",\"Front Light does\\u0027nt work\"]",
                            HasAllComponents = 1,
                            ItemType = 2,
                            MissingComponents = "[]",
                            MissionCapable = 1,
                            SerialNumber = "367N2"
                        },
                        new
                        {
                            Id = new Guid("05eb7f71-cc56-48c9-b886-2d3a9352057c"),
                            CheckedOut = 2,
                            Defects = "[]",
                            HasAllComponents = 2,
                            ItemType = 1,
                            MissingComponents = "[\"Missing 2 stakes\",\"Missing one blue pole\"]",
                            MissionCapable = 2,
                            SerialNumber = "355N3"
                        },
                        new
                        {
                            Id = new Guid("9497ad4e-6814-4350-93db-d7ad6b700562"),
                            CheckedOut = 2,
                            Defects = "[]",
                            HasAllComponents = 1,
                            ItemType = 1,
                            MissingComponents = "[\"Missing 1 stake\",\"Missing 2 blue pole\",\"Missing Hammer\"]",
                            MissionCapable = 1,
                            SerialNumber = "557N2"
                        },
                        new
                        {
                            Id = new Guid("84af1935-628b-4203-b782-d9e9a56554d9"),
                            CheckedOut = 2,
                            Defects = "[\"Mic key does not work\"]",
                            HasAllComponents = 1,
                            ItemType = 3,
                            MissingComponents = "[]",
                            MissionCapable = 1,
                            SerialNumber = "363S2"
                        },
                        new
                        {
                            Id = new Guid("d3465f1a-3e4b-4a85-9cde-8fdc156885ac"),
                            CheckedOut = 2,
                            Defects = "[\"Back connectors bent\",\"Front Light does\\u0027nt work\"]",
                            HasAllComponents = 1,
                            ItemType = 2,
                            MissingComponents = "[]",
                            MissionCapable = 1,
                            SerialNumber = "867N2"
                        },
                        new
                        {
                            Id = new Guid("53d080d3-6ebc-4b97-abd4-e0e3daebbd26"),
                            CheckedOut = 2,
                            Defects = "[]",
                            HasAllComponents = 1,
                            ItemType = 1,
                            MissingComponents = "[\"Missing 2 stakes\",\"Missing one blue pole\"]",
                            MissionCapable = 1,
                            SerialNumber = "865N3"
                        },
                        new
                        {
                            Id = new Guid("a1ca67d1-265e-473c-8087-e33660de8cae"),
                            CheckedOut = 2,
                            Defects = "[]",
                            HasAllComponents = 1,
                            ItemType = 5,
                            MissingComponents = "[\"Missing 1 stake\",\"Missing 2 blue pole\",\"Missing Hammer\"]",
                            MissionCapable = 1,
                            SerialNumber = "637N2"
                        },
                        new
                        {
                            Id = new Guid("fb9540a3-33b8-4d0a-8d06-6ff3946befd6"),
                            CheckedOut = 2,
                            Defects = "[\"Mic key does not work\"]",
                            HasAllComponents = 1,
                            ItemType = 3,
                            MissingComponents = "[]",
                            MissionCapable = 1,
                            SerialNumber = "467N9"
                        });
                });

            modelBuilder.Entity("ArmoryInventory.Domain.Models.Checkout", b =>
                {
                    b.HasOne("ArmoryInventory.Domain.Models.Item", "Item")
                        .WithMany("CheckoutHistory")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");
                });

            modelBuilder.Entity("ArmoryInventory.Domain.Models.Item", b =>
                {
                    b.Navigation("CheckoutHistory");
                });
#pragma warning restore 612, 618
        }
    }
}
